### PR TITLE
docs(contributions): add contributions stats

### PR DESCRIPTION
**Pull request by lucasaarcoverde**
## Summary

Add the contributions activity to the shoreline documentation.

* Activity page with a list of all shoreline active contributors and a list of the most commented open issues
* Contributor page with stats of contribution

## Examples

https://github.com/user-attachments/assets/3112423a-77f7-4200-936b-f67c0849330f

### CODE REVIEW

**Review by beatrizmilhomem — COMMENTED** [review]
If possible, before the release:
- Change the radius from the `Issues on fire` and `Contributions` cards to 12px.
- Horizontally align the issue green symbol with its title.
- Add a breadcrumb on top of the Contributor page.

**Comment by davicostalf** [comment]
- What is the criteria that was implemented to show issues on fire? By last interaction?
- To open a issue I had to click on an empty space in the line. Clicking in the name of the issue didn't trigger the link.

**Comment by lucasaarcoverde** [comment]
> What is the criteria that was implemented to show issues on fire? By last interaction?

The criteria is the open issues with most comments. We can think of a better criteria later 🤔 

> 1. To open an issue I had to click on an empty space in the line. Clicking in the name of the issue didn't trigger the link.
> 2. Change the radius from the Issues on fire and Contributions cards to 12px.
> 3. Horizontally align the issue green symbol with its title.

Done!

> Add a breadcrumb on top of the Contributor page.

I don't know an easy way of doing this for now. The contributor page it isn't under the `Activity` scope in the code because if I add them under `Activity` they will be shown in the sidebar, something like this:

```
- Activity
  |_ marcelovicentegc
  |_ anitavincent
   ...
```

So I added them under the `Contributors` scope, which I can hide on the sidebar

cc @davicostalf @beatrizmilhomem

**Review by davicostalf — APPROVED** [review]
LGTM

**Pull request merged**
